version: '3.1'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.2.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    ports:
      - "29092:29092"
    image: confluentinc/cp-kafka:3.2.0
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
  fdns-ms-reporting-archiver:
    image: cdcgov/fdns-ms-reporting-kafka
    environment:
      PROFILE_NAME: ARCHIVER
      GROUP_NAME: reporting-archiver-group
      INCOMING_TOPIC_NAME: reporting-archiver
      ERROR_TOPIC_NAME: reporting-error
      KAFKA_BROKERS: kafka:29092
      STORAGE_URL: http://fdns-ms-storage:8082
      OBJECT_URL: http://fdns-ms-object:8083
      INDEXING_URL: http://fdns-ms-indexing:8084
  fdns-ms-reporting-combiner:
    image: cdcgov/fdns-ms-reporting-kafka
    environment:
      PROFILE_NAME: COMBINER
      GROUP_NAME: reporting-combiner-group
      INCOMING_TOPIC_NAME: reporting-combiner
      ERROR_TOPIC_NAME: reporting-error
      KAFKA_BROKERS: kafka:29092
      STORAGE_URL: http://fdns-ms-storage:8082
      OBJECT_URL: http://fdns-ms-object:8083
      INDEXING_URL: http://fdns-ms-indexing:8084
      COMBINER_URL: http://fdns-ms-combiner:8085
      MICROSOFT_UTILS_URL: http://fdns-ms-msft-utils:8086
  # NOTE: These services depend on additional FDNS containers running that may be difficult in a low memory environment
  # Please see the docker-compose.yml for more information on dependent services